# Generated by Django 3.0.3 on 2020-03-01 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='coordinates',
        ),
        migrations.AddField(
            model_name='room',
            name='x_coord',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='y_coord',
            field=models.IntegerField(default=0),
        ),
    ]
